[package]
name = "FinSc-Multiset-Ternary"
version = "0.3.0"
ipkg = "FinSc-Multiset-Ternary.ipkg"

[custom.all.FinSc-Multiset-Core]
type = "local"
path = "../FinSc-Multiset-Core"
ipkg = "FinSc-Multiset-Core.ipkg"

[custom.all.FinSc-Multiset-Binary]
type = "local"
path = "../FinSc-Multiset-Binary"
ipkg = "FinSc-Multiset-Binary.ipkg"
